### ISSUE TITLE
Handling multiple languages - Zanskar

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#28]
How do we handle the various languages that are spoken/understood in context of mesh design in Zanskar. 

Spoken languages - Zanskari (similar to Ladakhi), Urdu, Hindi, English (in that order)
Written languages - ?
Languages used in school - ?

How do we go about designing apps / services with this knowledge in mind.

**Comment by mikkokotila** [comment]
One of the things we did not discuss yesterday is how at least in Ladakh (and widely in India) Hindi is ok as a spoken language. 

The question about designing apps / services...I think the idea we've had for some time i.e. avoid "content" and instead provide tools that empower (e.g. phone calls) is useful here. Say we have a "rule" that whatever we introduce is language agnostic (like calls) it entirely solves the language problem. Which is otherwise a big obstacle because we end up depending on various local language experts.

**Comment by m-anish** [comment]
> I think the idea we've had for some time i.e. avoid "content" and instead provide tools that empower (e.g. phone calls) is useful here. Say we have a "rule" that whatever we introduce is language agnostic (like calls) it entirely solves the language problem

I agree with this in spirit, but we still probably need to think about it, for example, in the context of [this](https://github.com/eka-foundation/blockable)

**Comment by mikkokotila** [comment]
Sure, it is an important question to think about related with a GUI focused API. I've created an [issue](https://github.com/eka-foundation/blockable/issues/2) for it.

**Comment by m-anish** [comment]
Wonderful. I think this issue is best handled by the one you opened, in the repo that you opened. Closing this.
